version: "3"

dotenv: [".env"]

env:
  GOOGLE_APPLICATION_CREDENTIALS: "{{.TASKFILE_DIR}}/secrets/functions_credentials_file.json"

tasks:
  default:
    silent: true
    desc: "Print available commands"
    cmd: task --list-all --sort none

  lint:
    desc: "Lint all files in the repository"
    cmd: pre-commit run --all-files

  test:
    desc: "Run tfsec for all modules"
    deps: [authenticate]
    dir: ./src/terraform
    cmds:
      - tfsec --soft-fail
      - task clean-credential-key

  build:
    desc: "Run terraform plan on all modules"
    dir: src/terraform
    deps: [authenticate]
    cmds:
      - task prepare-functions
      - terraform init
      - terraform plan -out tf.plan
      - task clean-credential-key

  deploy:
    desc: "Run terraform apply"
    deps: [authenticate]
    dir: src/terraform
    cmds:
      - terraform init
      - terraform apply  tf.plan
      - task clean-credential-key
      - rm -f tf.plan
      - cd "{{.TASKFILE_DIR}}" && find "src/dist_functions" -type f -not -name ".gitkeep" -delete
      - cd "{{.TASKFILE_DIR}}" &&  find "src/dist_functions" -type d -empty -delete

  authenticate:
    desc: "Authenticate to gcloud project"
    cmds:
      - task write-credential-key
      - gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS

  write-credential-key:
    desc: "Create GCP credential file from base64 variable"
    silent: true
    requires:
      vars:
        - GOOGLE_SERVICE_ACCOUNT_BASE64
    dir: "{{.TASKFILE_DIR}}"
    cmd: echo "$GOOGLE_SERVICE_ACCOUNT_BASE64" | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS

  clean-credential-key:
    desc: "Delete GCP credential file"
    silent: true
    dir: "{{.TASKFILE_DIR}}"
    cmd: rm -f $GOOGLE_APPLICATION_CREDENTIALS

  prepare-functions:
    desc: "Prepare functions for deployment"
    deps: [authenticate]
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - bash prepare-files.sh
