name: "Deployment Infra"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.9.0

      - name: testing
        run: devbox run task prepare-functions

      - name: testing-functions
        run: ls -la "src/dist_functions"
      # - name: Lint action
      #   run: devbox run task lint

      # - name: Test action
      #   run: devbox run task test

      # - name: Build
      #   id: build
      #   run: devbox run task build

      # - name: Deploy
      #   id: deploy
      #   run: devbox run task deploy
